add sanity check plugin and proof the config is picked up correctly

diff --git a/bin/stile b/bin/stile
--- a/bin/stile
+++ b/bin/stile
@@ -1,15 +1,19 @@
 #!/bin/bash
 
+function fail() {
+  usage $*
+  exit 77
+}
+
 function usage() {
   echo $*
   echo
   echo "Stile: a maven simplifier"
-  exit 77
 }
 
 function configure() {
-  test "$1" = "/" && usage "Could not find .stilerc in hierarchy"
-  if test -d $1/.stilerc; then 
+  test "$1" = "/" && fail "Could not find .stilerc in hierarchy"
+  if test -f $1/.stilerc; then 
     source $1/.stilerc
   else
     configure $(dirname $1)
@@ -17,11 +21,17 @@ function configure() {
 }
 
 function load() {
-  test -d ~/.stile/plugins/$1 || usage "Plugin $1 not found"
-  test -f ~/.stile/plugins/$1/$1 || usage "Plugin $1 not found"
+  test -d ~/.stile/plugins/$1 || fail "Plugin $1 not found"
+  test -f ~/.stile/plugins/$1/$1 || fail "Plugin $1 not found"
   source ~/.stile/plugins/$1/$1
 }
 
+if test "$1" = "usage"; then
+  usage "stile <plugin> [debug]"
+  exit 0
+fi
+
+test "$2" = "debug" && set -x
 
 test "$1" = "stile-verify" || configure $(pwd)
 
diff --git a/plugins/stile-verify/stile-verify b/plugins/stile-verify/stile-verify
--- a/plugins/stile-verify/stile-verify
+++ b/plugins/stile-verify/stile-verify
@@ -14,6 +14,12 @@ function stile-verify() {
     fi
     popd > /dev/null
   done
-  
-  test "$failed" = "0" || exit 77
+
+  echo  
+  if test "$failed" = "0"; then
+    echo "PASSED"
+  else
+    echo "FAILED"
+    exit 77
+  fi
 }
